services:
  - type: web
    name: dynesis-tech-backend
    env: node
    plan: free
    rootDir: .
    buildCommand: npm ci
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
